# Site settings
title: Chowdown
email: mkirsch42@gmail.com
description: The plain text recipe database for hackers
baseurl: "https://chow.koosh.xyz"
language: "en"
lang_direction: "ltr"
color: &site-color "maroon"
github_username:  mkirsch42
github_url: https://github.com/mkirsch42/chowdown

defaults:
  -
    scope:
      type: "recipes"
    values:
      color: *site-color

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="!!!">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
    references: "Adapted from"
    recipe_yield: "Yields"
    tags: "Tags"
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    blog: "Blog"
    subscribe: "Abonnieren"